name: idn_solo_dart_challange
description: IDN Solo Dart Fundamental Challange
version: 1.0.0
repository: https://github.com/iyxan23/idn-solo-dart-challange

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
